//****************************************************************************
// Model: Uart.qm
// File:  Uart/UartIn.h
//
// This code has been generated by QM tool (see state-machine.com/qm).
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//****************************************************************************
//${Uart::Uart::UartIn.h} ....................................................
#ifndef UART_IN_H_
#define UART_IN_H_
#include "qpcpp.h"
#include "macros.h"
#include "active_events.h"
#include "active_pipe.h"
#include "bsp.h"
using namespace QP;
using namespace StdEvents;

namespace AOs {
    enum{
        UART_IN_ACTIVE_TIMER_MS = 10
    };
}
namespace AOs {


#if ((QP_VERSION < 580) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpcpp version 5.8.0 or higher required
#endif

//${Uart::UartIn} ............................................................
class UartIn : public StdEvents::ASM {
protected:
    Fifo * m_fifo;
    USART_HANDLE_TYPE_DEF * m_devUart;
    bool m_dataReady;

public:
    enum {STARTING_STOPPING_TIMEOUT = 200};

public:
    UartIn(
        QP::QActive * owner,
        Fifo * fifo,
        USART_HANDLE_TYPE_DEF * devUart);
    static void DmaDoneCallback();
    static void DmaHalfDoneCallback();
    static void DmaDataReadyCallback();

protected:
    static QP::QState initial(UartIn * const me, QP::QEvt const * const e);
    static QP::QState Root(UartIn * const me, QP::QEvt const * const e);
    static QP::QState Stopped(UartIn * const me, QP::QEvt const * const e);
    static QP::QState Started(UartIn * const me, QP::QEvt const * const e);
    static QP::QState Failed(UartIn * const me, QP::QEvt const * const e);
    static QP::QState Normal(UartIn * const me, QP::QEvt const * const e);
    static QP::QState Active(UartIn * const me, QP::QEvt const * const e);
    static QP::QState Inactive(UartIn * const me, QP::QEvt const * const e);
};

} // namespace AOs

#endif
