//****************************************************************************
// Model: StdEvents.qm
// File:  stdevents/active_config.h
//
// This code has been generated by QM tool (see state-machine.com/qm).
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//****************************************************************************
//${stdevents::active_config.h} ..............................................
#ifndef ACTIVE_CONFIG_H
#define ACTIVE_CONFIG_H

#include "macros.h"

#ifdef __cplusplus
extern "C" {
#endif

void QP_PreInitialize(void);

int QP_InitializeRun(void);

void QP_StartActiveObjectsAndPublishBootTimeEvents(void);

void QP_AllocateSubscriberLists(void);

void QP_AllocateMemoryPools(void);

#ifdef __cplusplus
}
#endif

#endif // ACTIVE_CONFIG_H

